### ISSUE TITLE
[Mining] Help prompt next to Merged mining title

### ISSUE THREAD

**Issue by tomaszantas** [Altalogy/tari#185] opened 2022-05-18 15:15 UTC
Add Help prompt:

![image](https://user-images.githubusercontent.com/11715931/169077084-4f0daa7f-f699-4067-8cab-e2bcc5acf1ef.png)

**Comment by tarnas14** [comment] 2022-05-20 11:35
looks like a duplicate of #44

**Comment by tomaszantas** [comment] 2022-05-20 12:13
I believe that #44 is to this one:

![image](https://user-images.githubusercontent.com/11715931/169525833-9a699d20-a3cf-4a36-90d8-2ab0b44d195b.png)

Still both issues can be merged, or we can keep them separately

**Closed as completed** 2022-06-10 10:22 UTC
