### ISSUE TITLE
Main tabs bottom border animation breaks

### ISSUE THREAD

**Issue by tarnas14** [Altalogy/tari#337] opened 2022-06-28 13:55 UTC
When multiple tabs are animated, change state etc, the accented border below tabs breaks its animation as if not enough renders where done due to state changes, example below

make sure it actually happens consistently without expert view open
and check on other OS than linux

![cleanup](https://user-images.githubusercontent.com/9142942/176196665-053a196d-7c4d-47f9-b00b-e24fcfb61d17.gif)

**Comment by tomaszantas** [comment] 2022-07-15 08:37
I can't reproduce this error, and I didn't found this error during the last 2 weeks of development. 
Closing for now since it's not a critical bug (not crashing the app), and could not be reproduced.

**Closed as completed by tomaszantas** 2022-07-15 08:37 UTC
Labels: bug
